qube_version: '2.6.1 # <<QUBE_NO_BUMP>>'
full_name: Andreas Friedrich
email: andreas.friedrich@qbic.uni-tuebingen.de
project_name: ProjectWizard Portlet
project_short_description: Creates hierarchical experiments using factorial design.
version: 1.10.0-SNAPSHOT
domain: portlet
language: groovy
project_slug: ProjectWizard_Portlet
project_slug_no_hyphen: ProjectWizard_Portlet
template_version: '1.0.4 # <<QUBE_NO_BUMP>>'
template_handle: portlet-groovy
github_username: wow-such-code
creator_github_username: wow-such-code
is_github_repo: false
is_repo_private: false
is_github_orga: false
copyright_holder: QBiC
license: MIT
main_class_prefix: ProjectWizard
use_openbis_client: yes
use_openbis_raw_api: yes
use_qbic_databases: yes
use_vaadin_charts: no
